/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VolumesVolumeIdRouteImport } from './routes/volumes.$volumeId'
import { Route as VolumesNewRouteImport } from './routes/volumes.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumesVolumeIdRoute = VolumesVolumeIdRouteImport.update({
  id: '/volumes/$volumeId',
  path: '/volumes/$volumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumesNewRoute = VolumesNewRouteImport.update({
  id: '/volumes/new',
  path: '/volumes/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/volumes/$volumeId': typeof VolumesVolumeIdRoute
  '/volumes/new': typeof VolumesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/volumes/$volumeId': typeof VolumesVolumeIdRoute
  '/volumes/new': typeof VolumesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/volumes/$volumeId': typeof VolumesVolumeIdRoute
  '/volumes/new': typeof VolumesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library' | '/login' | '/volumes/$volumeId' | '/volumes/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/login' | '/volumes/$volumeId' | '/volumes/new'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/volumes/$volumeId'
    | '/volumes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  VolumesVolumeIdRoute: typeof VolumesVolumeIdRoute
  VolumesNewRoute: typeof VolumesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volumes/$volumeId': {
      id: '/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/volumes/$volumeId'
      preLoaderRoute: typeof VolumesVolumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volumes/new': {
      id: '/volumes/new'
      path: '/volumes/new'
      fullPath: '/volumes/new'
      preLoaderRoute: typeof VolumesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  VolumesVolumeIdRoute: VolumesVolumeIdRoute,
  VolumesNewRoute: VolumesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
